### ISSUE TITLE
Feature Request: Average Read Latency

### ISSUE THREAD

**Issue by Cameri** [dskvr/nostr-watch#100]
The instant read latency is affected by the current network conditions and is jittery.
An average read latency could be calculated perhaps using a sliding window (or just adding up previous reads), whenever we "check" with the relay again.

**Comment by dskvr** [comment]
A bit of work is being done in this area. It is related to #19

**Comment by dskvr** [comment]
PR #190 will likely address this request

**Comment by dskvr** [comment]
@Cameri If you're interested, I got pretty far on this. You can check out the progress here: #190  (check the netlify preview)  

Ignore the uptime stuff, that won't be functional/beautiful until a bit later.
