### ISSUE TITLE
Feature Request: Pinned Relays

### ISSUE THREAD

**Issue by Cameri** [dskvr/nostr-watch#101]
I wish I could pin my favorite relays to the top and let the rest get sorted by the algorithm.

**Comment by dskvr** [comment]
Thanks for the request. There's definitely an easy way to support pins, will try to find time to add it.

**Comment by dskvr** [comment]
Unfortunately, this improvement will need to wait until I transition everything to `pinia` as it will complicate the transition if I patch it in now. Was hoping to get it in tonight for ya, sorry about that.

**Comment by dskvr** [comment]
I will be integrating this in a different way when https://github.com/nostr-protocol/nips/pull/32 is merged. 

Behavior is like so: The site will display **your** relays, and you will be able to add and remove them at will. These changes will reflect in `NIP-23` supported clients.

Sidenote: i submitted an RFC for a simpler solution than `NIP-23` [here](https://github.com/nostr-protocol/nips/pull/32), if that gets any kind of traction and it makes sense to submit a NIP, I will be implementing that NIP as well/instead.

Cheers

**Comment by dskvr** [comment]
I have implemented pinned relays (favorites) in the refactor, which will release as 0.1.0. I estimate another 2 days of development and 2 days of optimization before release.

**Comment by dskvr** [comment]
@Cameri This feature was deployed to https://next.nostr.watch, let me know if it works for you.

**Comment by Cameri** [comment]
Thanks!
