### ISSUE TITLE
Relay added twice

### ISSUE THREAD

**Issue by ilazaridis** [dskvr/nostr-watch#115]
After last PR, 2 new entries added

- wss://nostr.hackerman.pro
- wss://nostr.hackerman.pro. 

The latter one accidentaly I guess.

Thank you in advance!

**Comment by dskvr** [comment]
Thank you! I noticed it around the same time as you :D

It's actually because at build-time we scan `kind: 3` events and someone shared the url with a period at the end. Just need to sanitize the URLs better before generating a uniques `Set()`. Will push within the hour. 

Thanks again.

**Comment by dskvr** [comment]
This has been resolved, will be live in a few minutes. thanks again for the attention to detail!

**Comment by dskvr** [comment]
Forgot to mention, you'll need to clear local data and manually refresh (click "gear" icon, click "clear local data")
