### ISSUE TITLE
Can't yarn  build because nostr.watch is down

### ISSUE THREAD

**Issue by gourcetools** [dskvr/nostr-watch#129]
Nostr.watch was unstable so i tought i deploy my copy but hey... i got this error. ^^

 
> $ yarn build
> yarn run v1.22.15
> $ yarn get:relays && yarn get:geo
> $ node ./scripts/relays.js
> FetchError: **request to https://nostr.watch/relays.json** failed, reason: connect ECONNREFUSED 46.101.217.80:443
>     at ClientRequest.<anonymous> (C:\user\nostr-watch\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1491:11)
>     at ClientRequest.emit (events.js:375:28)
>     at TLSSocket.socketErrorListener (_http_client.js:475:9)
>     at TLSSocket.emit (events.js:375:28)
>     at emitErrorNT (internal/streams/destroy.js:106:8)
>     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
>   type: 'system',
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED'
> }

**Comment by dskvr** [comment]
Hey there, sorry about that. Need to patch so there's no HTTP dependency. You can run

**Comment by gourcetools** [comment]
Wow such fast!
` ./node_modules/.bin/vue-cli-service serve `
Thank you! im not used to this.
Happy new years guys

**Comment by dskvr** [comment]
Happy new year!

**Comment by dskvr** [comment]
Just FYI, the hotfix resolved the http dependency, so `yarn build` would work. But that will include the prebuild which is a bit slow because it scans nostr for relays, tests each one and then retrieves geo data. The site will work without the `prebuild`, but may be missing some information/relays.
