### ISSUE TITLE
Stuck on loop fetching nostr.json

### ISSUE THREAD

**Issue by ricardocabralm** [dskvr/nostr-watch#172]
**Describe the bug**
If NIP-05 nostr.json fails, nostr.watch get's stuck fetching it over and over again.
Nothing else works after that happens.

**To Reproduce**
See the console logs for:
https://nostrex.fly.dev/.well-known/nostr.json

**Expected behavior**
nostr.watch should retry the failed nostr.json with an exponential backoff and bail after 3 to 5 tries.

**Screenshots**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/106993939/211394050-c2eb4a11-a380-43ac-81d6-f0167f88f246.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Additional context**

**Comment by dskvr** [comment]
The fix will be on http://next.nostr.watch in a few moments, after I've confirmed everything is good and there's no migration issues, I'll push to production. 

Thanks again!

**Comment by dskvr** [comment]
Had to do a bit more work than anticipated, however, the production deploy is now in progress.
