### ISSUE TITLE
Support detail page for non-SSL relays

### ISSUE THREAD

**Issue by Asone** [dskvr/nostr-watch#188]
**Is your feature request related to a problem? Please describe.**
As i am experimenting nostr applications onto an umbrel node i've loaded nostr-watch to monitor the relay i loaded onto the node. 

The app seems to be able to detect the relay while on the main page of app. 

<img width="1389" alt="Capture d’écran 2023-01-10 à 22 06 35" src="https://user-images.githubusercontent.com/441960/211663691-405a1ee2-8d6b-4c6a-b31e-6c41f192b2d1.png">

once i try to load the detail page, the node is declared as being offline by the app. 

I suspect the detail page does not detect `ws://` as the protocol and tries to ping `wss://ws://umbrel.local` instead, which obviously fails.

<img width="759" alt="Capture d’écran 2023-01-10 à 22 12 45" src="https://user-images.githubusercontent.com/441960/211663842-1780e3ae-bda6-42ce-9481-2008a59f89b6.png">

**Describe the solution you'd like**
To have either the app considering `ws://` on behalf of the already supported `wss://` urls. 

**Describe alternatives you've considered**
Let users write the whole urls and avoid the app to do the url parsing

**Comment by dskvr** [comment]
I actually haven't implemented dynamic routes to discover relays, but it's an amazing a simple idea. 

Regarding supporting a WS relay from HTTPS, it's impossible without setting a series of flags in your browser, as your browser will simply not allow you to connect to an insecure node from HTTPS. 

1. This contradicts a previous request, would have to allow HTTP (JUST NOTICED HTTP IS NO LONGER REDIRECTING BTW!!! Thanks for accidentally bringing that regression to my attention)
2. It is not a use case most people would need, as it's a real pain to coax a browser to connect to an insecure websocket from HTTPS.

That said, dynamic routes for undiscovered relays is a winner.

Also, there's no reason why you wouldn't be able to setup SSL locally from umbrel, let me know if you need some tips.

**Comment by dskvr** [comment]
Wait, if you're also running nostr.watch from umbrel, then yeah, it would work. So with that in mind, I can make some minor modifications so this would work. 

Please clarify.

**Comment by dskvr** [comment]
@asone I added ws:// support in the following branch but it will only work if you run nostr.watch locally due to the browser limitations I mentioned before. 

The preview builds deploy via netlify, which support **https only**, I don't have control over there. Instructions for usage are in PR. Let me know if it works for you. 

https://github.com/dskvr/nostr-watch/pull/191

**Comment by dskvr** [comment]
I tested locally with success, it's now in the develop branch.

**Comment by dskvr** [comment]
@Asone  Did you try it out by chance?

**Comment by dskvr** [comment]
HTTP is still accessible via nostr.watch, so you could test without even pulling

http://nostr.watch/relay/ws/umbrel.local:6837
