### ISSUE TITLE
Implement signing in to see own favourite relays

### ISSUE THREAD

**Issue by Cameri** [dskvr/nostr-watch#189]
**Is your feature request related to a problem? Please describe.**
Please implement window.nostr to sign in, and once signed in, show relays from one's self `kind 3` event `content` field.

**Describe the solution you'd like**
1. Allow signing in using a Nostr extension: Alby, nos2x, Blockcore Wallet.
2. Once signed in, fetch the `kind 3` event from the user's pubkey.
3. Show relays selected as pinned/favourite.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dskvr** [comment]
Hey Cameri,

This should already work! If it doesn't there's a bug. Top right, "sign in" link should appear after about 500ms, works with all the Nostr extensions I tested. 

Additionally, #185 is a demo of NIP-23, which is almost identical to this request

I really don't want to use Kind 2 relay lists, because each client implements it differently. Some of them grab the newest event, some grab an event they've tagged as theirs. It's a minefield, I need NIP-23 (hence escalating NIP-23 here: https://github.com/nostr-protocol/nips/pull/164)

**Comment by dskvr** [comment]
...Continued

The only way I can see making Kind 2 work with "relay curation" is if I requested all the kind 2's someone had,  merged them into one kind 2 event, asked them to delete all the existing ones, and then published it.  Other than requiring tens of event signings, this would probably break a bunch of clients and would probably not end well.

Going off topic...

<begin rant>

What's happening with Clients right now is somewhat predictable. They are naturally competing, and so they either wait for a standard to pass, or they make their own standard. This breaks interoperability. Additionally, interoperability is not competitive, it's cooperative. Not being cooperative is a competitive advantage unless the community has their say. 

These two paradigms can absolutely coexist, but there needs to be separation of concerns. 

1. A standard is agreed up
2. We do the work to inform users
3. The users put the pressure on the clients, which in turn leads to adoption.

If we try to do it in reverse order, it has a far lower probability of success. 

From where I'm standing, I cannot just write my own standard, as it would have no meaning

</end rant>

**Comment by Cameri** [comment]
> ...Continued
> 
> 
> 
> The only way I can see making Kind 2 work with "relay curation" is if I requested all the kind 2's someone had,  merged them into one kind 2 event, asked them to delete all the existing ones, and then published it.  Other than requiring tens of event signings, this would probably break a bunch of clients and would probably not end well.
> 
> 
> 
> Going off topic...
> 
> 
> 
> `<begin rant>`
> 
> 
> 
> What's happening with Clients right now is somewhat predictable. They are naturally competing, and so they either wait for a standard to pass, or they make their own standard. This breaks interoperability. Additionally, interoperability is not competitive, it's cooperative. Not being cooperative is a competitive advantage unless the community has their say.  Hence, we are here.
> 
> 
> 
> These two paradigms can absolutely coexist, but there needs to be separation of concerns. 
> 
> 
> 
> 1. A standard is agreed up
> 
> 2. We do the work to inform users
> 
> 3. The users put the pressure on the clients, which in turn leads to adoption.
> 
> 
> 
> If we try to do it in reverse order, it has a far lower probability of success. 
> 
> 
> 
> From where I'm standing, I cannot just start throwing events at the wall, as it would have no meaning and cause more issues. That's why I'm working on implementing NIP-23, because then at least there's a canonical and a working example to start from.
> 
> 
> 
> `</end rant>`

Kind 2 is a replaceable event, there should be only one per pubkey. If you get many from multiple relays you keep the one with the greatest created_at date

**Comment by dskvr** [comment]
Bro... what? I can find nothing that mentions this anywhere, not in the NIP. Do you have a link to something? If that's the case, I can probably have it up tomorrow.

Did the login work for you?

**Comment by Cameri** [comment]
@dskvr XD You are 100% correct, it isn't anywhere. But if you look at `kind 3` events `content` field (NOT the Nostr protocol), that's where relay configuration is saved by most clients today.
Example:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/378886/211721222-7cb7c8ce-fb05-48bd-855b-55441b0d6f97.png">

There is however a PR (and I also saw yours) that was going to address this in a better way: https://github.com/nostr-protocol/nips/pull/32

Also: Login does work for me! Thanks

**Comment by dskvr** [comment]
Yes, been participating in that NIP and submitted a PR to modify it since it was lagging. It's basically just a reduction of all all the discourse about NIP-23. Here: https://github.com/nostr-protocol/nips/pull/164

**Comment by dskvr** [comment]
Oh man ... The changes I submitted are only slightly different than the "kinda nip-2, oh nip-3 not really really nip-3 but sorta" kind. My proposal is middle group between the previous "renegade kind" and NIP-23, since they are strings not boolean. This seems like a good compromise as it enables extension with runes in another NIP down the road.

**Comment by Cameri** [comment]
I think we can close this for now, as I wouldnt want you to implement that stuff and then get rug pulled by the protocol xD

**Comment by dskvr** [comment]
I'm going to reopen, because it's still relevant to in-flight work.

**Comment by dskvr** [comment]
@Cameri Going to put this one on ice, after spending all day implementing, there's no way I will be introducing NIP-23a as-is to this codebase. 

90% of the code that was written for NIP-23a would require maintenance doesn't need to exist. 

I also implemented 23b with and without URL formats
- the one with, which was inverted to normalized urls, was implemented with basically no business logic whatsoever, one line to reject an _invalid_ duplicate and another line to normalize a URL.
- The one without without requires many UX elements, user education/explanation, is prone to error, creates an infinite number of edge cases and increases the test coverage by an order of magnitude.

Until there's a sane standard I won't be implementing relay lists anytime soon. There are other more popular features I can implement quickly that bring value to the community. 

I'll consider posting a competing NIP to NIP-23 if I become motivated and find the energy.

I'll leave this open, as other people are likely to ask for it. 

Cheers.

**Comment by dskvr** [comment]
@Cameri I never fully responded to your comment above https://github.com/dskvr/nostr-watch/issues/189#issuecomment-1378240762

> But if you look at kind 3 events content field (NOT the Nostr protocol), that's where relay configuration is saved by most clients today.

Yes, I utilize kind 3 events for discovery at build time. I was previously deterred from using non-replaceable kinds, but after implementing nip-23 and also interfacing with empty debate arguments, this looks like heaven. 

If relay lists happen, there will need to be more demand for this feature.
