### ISSUE TITLE
https://nostr.watch/relays.json is missing

### ISSUE THREAD

**Issue by gourcetools** [dskvr/nostr-watch#215]
Hey devs, I cant see the list of relays at https://nostr.watch/relays.json anymore...

**Comment by dskvr** [comment]
Whoops! 

Made an oopsie, I'll look into that for you.

**Comment by dskvr** [comment]
Sorry for the delay. I'll need to convert the relay list from `yaml` to `toml`, sorry for the downtime.

**Comment by Cameri** [comment]
I'm also looking at toml for Nostream, nice

**Comment by dskvr** [comment]
Yeah, `yaml` ecosystem is totally screwed, none of the parsers are consistent. Not even `yaml-doctor` is consistent. When a `:` is in a string, the string entry requires to be escaped with double quotes, but doesn't require double quotes if there's no colon. It's a pain.

@gourcetools Again, sorry for everything, the timing wasn't great. I'm going to wrap this in with the API release (which is FAR more useful) and is related to in-flight work (#190)

**Comment by dskvr** [comment]
@gourcetools Some space from this over the last couple days helped, found a solution. Will be live in ~1 hour

**Comment by dskvr** [comment]
@gourcetools https://nostr.watch/relays.json

Keep your eyes peeled for the API release (several protocols, including on nostr) will likely be very useful for `nostr-bestrelays` 

Cheers, sorry again.

**Comment by gourcetools** [comment]
Hey, that's amazing ! Thank you for fixing this

**Comment by dskvr** [comment]
@gourcetools check out #276
