### ISSUE TITLE
Relays count seems wrong

### ISSUE THREAD

**Issue by gourcetools** [dskvr/nostr-watch#235]
Hey, i'm wondering why it shows 228 when the file contrain actually less...

![image](https://user-images.githubusercontent.com/120996278/213886494-9e8c779c-b007-4091-815b-866c63958482.png)
![image](https://user-images.githubusercontent.com/120996278/213886510-11acb182-8fd7-4d35-823c-d3604a55ead8.png)

any ideas?

**Comment by dskvr** [comment]
It's not incorrect. 

At build-time (soon at run-time) nostr-watch scans `kind 3` events to discover relays that [haven't been submitted](https://github.com/dskvr/nostr-watch/blob/develop/scripts/relays.js). There's actually substantially more than 228 (around 400), but the script doesn't add relays it cannot connect to such as 
- Tor (for now)
- IPv6 format (for now)
- Relays with typos
- insecure `ws://` 
- Valid relays in Kind 3 that are offline. 

In. `0.3.0` there will be some additional tabs that show Onion and "Invalid" relays, but doesn't test them. 

I'm also going to add `kind 2` discovery at some point. 

Around 1.1.0, I'll deploy to nostr.watch to tor that tests tor relays.

**Comment by dskvr** [comment]
What might be wrong however, is that the relays list served from `relays.json` does not include those ammended relays that were discovered (it used to) 

If I have time and it's an easy fix, I'll look into it.

But otherwise, time is better spent on the API.

**Comment by gourcetools** [comment]
Thank you for this complete answer. Nice roadmap. Will wait and see :+1:

**Comment by dskvr** [comment]
I've been slacking on publishing a roadmap because things change so quickly, will try and get one up this week and ping you.
