### ISSUE TITLE
Server-side persistent version

### ISSUE THREAD

**Issue by fiatjaf** [dskvr/nostr-watch#244]
nostr.watch is great and everybody loves it, but I think everybody would love nostr.watch much more if it had a server and a database and stored relay status, ongoing statistics and other goodies on the server side.

I wanted to ask this privately, but couldn't find any contact information.

Have you thought about doing it?

I was thinking of putting up a bounty for it on https://bountsr.org/, but I think it would be much better if this was done at nostr.watch directly instead of elsewhere by someone else.

**Comment by dskvr** [comment]
Hey @fiatjaf,

Your timing is impeccable. A server-side version has always been in the cards, and as of about 16 hours ago there is already some data persistence live on nostr.watch.

You can see that here with uptime: https://nostr.watch/relay/relay.stoner.com

My strategy has always been the following: 

1. Client-side first. By having a client-side first approach, I can guarantee availability of the service during network outages. It's far more difficult/impossible to bring down a simple client-side app than it is to bring down network infrastructure. However, this has limitations, particularly with network growth. 
2. A backend that supplements and replaces most the functionality available in the client-side. The client-side will be able to gracefully degrade to client-side processing if the backend goes down. The backend has two modes, a nostr driven mode and a traditional stack. 

Here's what i've been working on
1. API. The API is basically complete and all I need to do is the documentation and harden the server. It's fairly performant. 
2. History Infrastructure. It tracks various data points for relays; uptime, software versions, locations, changes to meta data, etc. And this one is quite interesting. 

That second part has been in the works for the better part of 6 weeks, but have had to go back and forth between what people want/need now and what I wanted to do in the future. 

If there's something you're not seeing, let me know. 

Cheers!

**Comment by dskvr** [comment]
Also, you can contact me at nostr@sandwich.farm or PM me via nostr.

**Comment by dskvr** [comment]
I've shifted my roadmap to include this in `0.2` instead of `0.3`.
