### ISSUE TITLE
Ability to have relay metadata refreshed

### ISSUE THREAD

**Issue by shawnyeager** [dskvr/nostr-watch#250]
When I first setup my relay, I naively missed that my config file had rolled back to default. So my pub key, contact email, etc. are incorrect on nostr-watch.

It would be useful to be able to force a refresh/rescan of relay metadata. Unless it's there and I've missed it.

**Comment by dskvr** [comment]
It rescans on every check, trying click "check now."  All data and functionality is client-side rn, so the database lives in your browser

**Comment by shawnyeager** [comment]
Thanks. I see a 'Check SSL', but I can't locate 'Check now'.

**Comment by dskvr** [comment]
@shawnyeager Right now the check now button is only on https://nostr.watch/find/relays 

you're on single relay page, which reloads data on every page load. Could you send me the relay you're having problems with so I can look into it?

**Comment by dskvr** [comment]
I'll check this out in a bit.

**Comment by dskvr** [comment]
@shawnyeager The information on nostr.watch appears to be correct. 

Here's the [reqbin](https://reqbin.com/x3mursdd)

Your relay is returning the default nostream NIP-11, so there's something happening on your side. @Cameri

**Comment by shawnyeager** [comment]
It did. Thank you for your help. 🙌🏼
