### ISSUE TITLE
Don't assume contact contains an email

### ISSUE THREAD

**Issue by dskvr** [dskvr/nostr-watch#259]
**Describe the bug**
Presently nostr.watch assumes `info.contact` is an email

**To Reproduce**

**Expected behavior**
instead detect contact type 
- Email (safe email) 
- Website (link target _blank) 
- Pubkey (link to a client) 
- Phone (dial protocol) 
- Other (text)

**Screenshots**
![Screen Shot 2023-01-30 at 12 05 22 AM](https://user-images.githubusercontent.com/299465/215360764-bf29c52b-13cf-410d-b78e-a11a180e6c35.png)

**Comment by mdavids** [comment]
I was about to open an issue, until I found this one.

Here's an example: https://nostr.watch/relay/nostr.sidnlabs.nl

https://github.com/nostr-protocol/nips/blob/master/11.md explains it well; the URI can also be https.
