### ISSUE TITLE
Feature request: implement REST API endpoint to allow discovery by apps

### ISSUE THREAD

**Issue by galets** [dskvr/nostr-watch#276]
**Is your feature request related to a problem? Please describe.**

Nostr presently has no simple ways to perform relay discovery. It would be a nice feature if apps would have a way to discover some of the relays using this nostr-watch via a single GET call, since it already has a list to start with.

**Describe the solution you'd like**

Provide an API endpoint, such as

```
GET /api/relays
response: [
 { "name": "nostr.supremestack.xyz", endpoint: "wss://nostr.supremestack.xyz", "NIP-11":... "Location": ... "Uptime(12h)" .., }
]
```

**Describe alternatives you've considered**

hardcode, manual discovery

**Additional context**

this is wrt a [messenger app](https://github.com/galets/nostr_message_fetch) I'm writing, but utility is not limited to that app alone

**Comment by dskvr** [comment]
For now, we have https://nostr.watch/relays.json 

The API is actually already complete, but I'm a bit bogged down right now and haven't had the time to deploy and harden the server. 

I'll update this issue when it's live.

**Comment by dskvr** [comment]
So I finally cracked. I deployed the API without documentation. I hardened the config a little, but no uptime guarantee for now. 

Here's the endpoints

**Availability**
https://api.nostr.watch/v1/online
https://api.nostr.watch/v1/offline

**Nip Support Examples**
https://api.nostr.watch/v1/nip/1
https://api.nostr.watch/v1/nip/15

**Comment by galets** [comment]
❤️

**Comment by dskvr** [comment]
It's `GET` only, no params. `v2` wil be a bit more robust.

**Comment by gourcetools** [comment]
This is not true that we can't discover relays... using the "recomand" we can ask all the "recommend" events and get relays...
The thing is that you won't have any relays without having a relay first... ^^

**Comment by dskvr** [comment]
@gourcetools Yes, this is true. But again kind 2 isn't as useful as kind 3 for this. Because kind 3 includes relays that people are actually using and requires sifting through less duplicates and events.
