### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by v0l** [dskvr/nostr-watch#290]
**Is your feature request related to a problem? Please describe.**
Trying to fetch online relays from Snort

**Describe the solution you'd like**
Please add CORS header to allow fetch from other sites

**Describe alternatives you've considered**
Hardcoded relay list?

**Additional context**
Spreading relay load

**Comment by dskvr** [comment]
Hey there!

there's a full list here (includes offline): https://nostr.watch/relays.json 

I didn't notice the CORS headers, will fix that for ya.

**Comment by dskvr** [comment]
This should now be resolved, let me know.

**Comment by v0l** [comment]
Fast! Working now thanks

**Comment by dskvr** [comment]
Closing this, may the force be with you.

**Comment by dskvr** [comment]
@v0l As a sidenote, consider fallback to https://nostr.watch/relays.json if the api is offline. Also, I have something a bit more useful than the REST API in the works, so follow me so you have a chance of seeing the announcement. Cheers!
