### ISSUE TITLE
Add Paid Relay Column & Attribute [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [dskvr/nostr-watch#354]
**Is your feature request related to a problem? Please describe.**
There is no easy way to check a list of relays that are paid, and there is no easy way to check if a particular relay is paid. Currently, nostr users sporadically aggregate to their best knowledge paid relays on notes.

## User Story ##
As a nostr.watch user who is researching paid relays, among a sea of thousands of relays I would like see all paid relays AND check if a particular relay is a paid relay, so that I can do my paid relay research and decide which relays I want to join.

**Describe the solution you'd like**
### Acceptance Criteria ###
1. Add paid relay attribute to relays
2. Add paid relay column
3. Nostr.watch can sort by paid relay status

**Describe alternatives you've considered**
Do nothing

**Additional context**
Stretch: 
-consider adding field to allow adding of specific relay admission price
-consider adding field to allow adding of URL to relay pay page

**Comment by dskvr** [comment]
This is part of the plan, however, NIP-11 needs to be amended first to include more data. Adding this feature is secondary too this.

**Comment by dskvr** [comment]
I've added a paid-relay column and tab. It's live on staging: https://next.nostr.watch/

**Comment by dskvr** [comment]
@alltheseas I used a dollar sign because there was an SVG available, and couldn't find a suitable alternative. Get me a  clean sats SVG and consider it done.

**Comment by dskvr** [comment]
Ah! sorry about that! I didn't inspect closely enough. Yeah, I'll push those tonight. Thanks!!!

**Comment by dskvr** [comment]
@alltheseas There you go, thanks for the assets! https://next.nostr.watch/relays/find
