### ISSUE TITLE
API for public relays

### ISSUE THREAD

**Issue by chmac** [dskvr/nostr-watch#362]
**Is your feature request related to a problem? Please describe.**
I'm looking to fetch a list of relays to connect to some at random. It would be awesome if I could grab a list of relays which are public (read) and online. I'd be happy if the online data was a bit out of date (served from cache).

**Describe the solution you'd like**
An endpoint like `/v1/onlinePublic` maybe?

**Describe alternatives you've considered**
I tried looking at just the `/online` relays, but they seem to outnumber all the relays listed on the web UI. I'm assuming there's some kind of filtering going on?

**Additional context**
It looks like there's a ton of `filter.nostr.wine` relays listed. Maybe the web UI is filtering those out somehow. I guess the same filters could also be applied to an API endpoint?

If you're open to PRs I might be able to put some time into this. But no guarantee on when (or if) that could happen, so not sure how valuable that is to you.

**Comment by dskvr** [comment]
> I tried looking at just the /online relays, but they seem to outnumber all the relays listed on the web UI. I'm assuming there's some kind of filtering going on?

https://nostr.watch and https://api.nostr.watch are not operating on the same data, however, https://next.nostr.watch (staging), is. That said, staging has a bug atm, appears to have stopped working. 

> It looks like there's a ton of filter.nostr.wine relays listed. Maybe the web UI is filtering those out somehow. I guess the same filters could also be applied to an API endpoint?

There are pay-to-relay relays. I haven't updated the discovery logic yet to filter these out. 

> If you're open to PRs I might be able to put some time into this. But no guarantee on when (or if) that could happen, so not sure how valuable that is to you.

The API code is not in this repo, and is not yet open source. When it's open-sourced I'll drop a message in this issue.

I'm really trying to get ahead of a number of issues on the horizon with the next release, so all my attention is focused there. Once I stablize the next release, I'm moving back over to the `nostrwatch-daemon`, with the goal of getting it open sourced.

Cheers.

**Comment by dskvr** [comment]
@chmac The list should be much better now, as *most* of the paid relay implementations have been cleared from the list.

**Comment by dskvr** [comment]
@chmac I pushed this a while ago and forgot to update this issue

https://api.nostr.watch/v1/public

cheers

**Comment by Myzel394** [comment]
@dskvr Going to https://api.nostr.watch/v1/public results in a 204 error - is the API currently down or am I doing something wrong on my side?
