### ISSUE TITLE
Opt-out Request

### ISSUE THREAD

**Issue by h3zjp** [dskvr/nostr-watch#416]
The relay server nostr.h3z.jp that I manage blocks IaaS such as AWS, GCP, DigitalOcean, etc. outside Japan,
I'm in trouble because the server of nostr.watch accesses regularly.
Please opt out so that the server of nostr.watch will not access it.

**Comment by dskvr** [comment]
If you have a public IP, your relay appears on lists and your relay responds, it will appear on nostr.watch. I will not be fulfilling removal requests, as this would be far too burdensome on a solo developer.

However, we may be able to use something like `Robots.txt` for opting out of checks.

I am slightly confused how you're in trouble for this, however. You have no control over who pings a Public IP address.

**Comment by dskvr** [comment]
Additionally, in the majority of the cases, nostr.watch checks are ran client-side, by the IP of each individual visitor. 

https://nostr.watch does have daemons that run checks as well, but this would be the vast minority.

**Comment by dskvr** [comment]
@h3zjp Please add 

```
User-agent: nostr.watch
Disallow: / 
```

To your `Robots.txt` text file, make one if it doesn't exist. 

For your relay, this would need to be accessible via https://nostr.h3z.jp/Robots.txt

I will try and get a patch out to the daemons tonight. 

To address the "being listed on nostr.watch," this would need to happen protocol level, a NIP would need to be submitted.

**Comment by h3zjp** [comment]
Thank you for your response.
I will add robots.txt and see what happens.

**Comment by dskvr** [comment]
Having some issues getting this implemented, as none of the `robots.txt` parsers on NPM appear to be functional.

**Comment by dskvr** [comment]
This has been implemented and will be deployed in a few hours.

**Comment by h3zjp** [comment]
👍
