### ISSUE TITLE
[BUG] Topics should be ignored if they are included in the 'Ignore Topics'

### ISSUE THREAD

**Issue by jilv220** [dskvr/nostr-watch#432]
**Describe the bug**
Topics should be ignored if they are included in the 'Ignore Topics', but they are not.

**To Reproduce**
1. Set the ignore topics
2. Go back to relays tab
3. The topics are still there

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/20714458/219980056-5616420d-5d3f-4567-a039-b576d7c9ccc2.png)

![image](https://user-images.githubusercontent.com/20714458/219980079-0ee03f6e-c842-4798-9ec1-161aefc58324.png)

**Desktop**
 - Garuda Linux
 - Brave
 - 1.48.164

**Comment by dskvr** [comment]
Thanks for the report, this appears to be a regression.

**Comment by dskvr** [comment]
@jilv220 This has been fixed on staging: https://next.nostr.watch/relays/find
