### ISSUE TITLE
Uptime daemon blocked?

### ISSUE THREAD

**Issue by middlingphys** [dskvr/nostr-watch#471]
I see the message:

> This relay does not have any uptime data. This is likely because the operator or their hosting provider has blocked nostr.watch uptime daemons.

on [my relay page](https://nostr.watch/relay/nostr.middling.mydns.jp), while the status is all green. What should I check to resolve this?

**Comment by dskvr** [comment]
Is your relay new?

**Comment by middlingphys** [comment]
It is added 4 days ago.

**Comment by dskvr** [comment]
Most likely it is because the asian deamons that generate this data are having issues. I've been working on the deamons the past week and am deploying some fixes now actually that will hopefully resolve the issue. It would take 12 hours for any noticable effect however.

**Comment by middlingphys** [comment]
OK then I will wait and see if it works.

**Comment by dskvr** [comment]
I have disabled uptime in production, so I'm going to close this now. Cheers!
