### ISSUE TITLE
Unable to browse - blank page  - runtime-core.esm-bundler.js

### ISSUE THREAD

**Issue by gourcetools** [dskvr/nostr-watch#514]
**Describe the bug**
Blank page.

**To Reproduce**
1. Go to '.nostr.watch.'
2. Click on '..open console.'
It all start with:
 
```
Error: BroadcastChannel: localstorage cannot be used
    at Object.oe [as create] (localstorage.js:84:11)
    at Te (broadcast-channel.js:198:37)
    at new xe (broadcast-channel.js:58:3)
    at yt (index.mjs:1:195)
    at index.mjs:1:891
    at Array.forEach (<anonymous>)
    at index.mjs:1:840
    at pinia.mjs:1644:43
    at o.run (reactivity.esm-bundler.js:34:24)
    at pinia.mjs:1644:33
```
 

**Expected behavior**
See the website.

**Screenshots**
Blank page.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser Chromium
 - Version 111.0.5563.110 (Official Build) snap (64-bit)

**Additional context**runtime-core.esm-bundler.js:228 TypeError: Cannot read properties of undefined (reading 'prefs')

![image](https://user-images.githubusercontent.com/120996278/227774107-e67f70ce-d92c-4c84-8f7b-48ba2a732e63.png)
![image](https://user-images.githubusercontent.com/120996278/227774129-550fb23d-e542-44ee-a2bd-8a7c22d4bb2a.png)

....
runtime-core.esm-bundler.js:228 TypeError: Cannot read properties of undefined (reading 'jobs')
runtime-core.esm-bundler.js:228 TypeError: Cannot read properties of undefined (reading 'prefs')
runtime-core.esm-bundler.js:228 TypeError: Cannot read properties of undefined (reading 'layout')

**Comment by dskvr** [comment]
I am unable to replicate. The server logs do indicate a 404 error for these files around this time (total of 23 errors for one IP, I'm guessing yours) while there are 50k+ 200 OKs for the same files within the same timeframe (>~0.1% error rate) 

This appears to have been a temporary server issue and not related to this repository. Will leave open for now. Please let me know if you are still experiencing this issue, if so, please try clearing cache.

**Comment by gourcetools** [comment]
I believe the unusual behavior is being caused by **my browser**. I apologize for not testing with a different profile on the same browser earlier. Now that I have done so, it appears to be functioning properly. Therefore, the issue may be related to a faulty plugin I am using or some other technical problem on my end.

**Comment by dskvr** [comment]
@gourcetools Maybe! Come to think of it, I think I have actually seen this error once when in the middle of a deploy (in between container restarts, ~1s). When I have the bandwidth I'll work out a zero-downtime deploy
