### ISSUE TITLE
Error not correcting 

### ISSUE THREAD

**Issue by CTCrypticThreadz** [dskvr/nostr-watch#549]
I accidently put Wws instead of wss I have since fixed it with a re commit. But my relay still shows up as wws on nostr.watch and I can't see any stats or anything for the new one. It's relay nostr.crypticthreadz.com

**Comment by dskvr** [comment]
PR #545 was merged into `main`, which deploys to production. While PR #547 was merged into `develop`, which deploys to [staging](https://next.nostr.watch)

**Comment by CTCrypticThreadz** [comment]
I think i did it right this time

**Comment by dskvr** [comment]
You did, it deployed. Technically my fault for not catching it in review. You will probbaly still see the old one in the list, it is because it's in localStorage on your browser. You can clear your local storage in preferences if it bothers you. Closing.
