### ISSUE TITLE
Map reset position

### ISSUE THREAD

**Issue by Norrun** [dskvr/nostr-watch#572]
**Describe the bug**
When I try to move the map, it snaps me back to the initial position all the time.
**To Reproduce**
1. Go to the map
2. try to move around
3. Observe as it snaps to initial position

**Expected behavior**
I expect it to move and stay h\where I moved it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi, Brave, Edge

**Comment by Norrun** [comment]
It resets the zoom too

**Comment by dskvr** [comment]
Thanks for your report. It's a known issue that was resolved, but then regressed. I'll try and patch it today.

**Comment by dskvr** [comment]
I just pushed a hotfix, will be deployed in ~10m. Resolved the issue locally, but please confirm the issue is resolved on your end. Cheers.
