### ISSUE TITLE
relay status incorrect

### ISSUE THREAD

**Issue by dasiyes** [dskvr/nostr-watch#606]
When I visit the main page (https://nostr.watch/relays/find), I often see my relay (https://nostr.ivmanto.dev) with the status OFFLINE. However, if I click on the relay itself and see the details - everything is green, and the relay is shown with the status online and all details correct.

**Comment by dskvr** [comment]
This is a known issue. I have some time this afternoon to look into it. Thanks for the issue.

**Comment by dskvr** [comment]
I think I found the issue. Problem was that relay discovery was missing a key datapoint. Changes need to propagate, will take about 30 minutes for me to confirm if the fix worked. Will let you know.

**Comment by dskvr** [comment]
Should be resolved now. There was a large spike of online relays in the `asia-south` and `eu-west` daemons, other daemons will catch up very soon. 

Problem was that the API daemon, which propagates to the publisher daemons, was not checking the bootstrap (relays.yaml). Closing. Will reopen 

![Screen Shot 2023-07-20 at 8 05 56 PM](https://github.com/dskvr/nostr-watch/assets/299465/af301a0d-b709-4f92-bef1-ec45c5dcbd39)
