### ISSUE TITLE
Apply to opensats

### ISSUE THREAD

**Issue by alltheseas** [dskvr/nostr-watch#638]
Apply to https://opensats.org/ to have server & operational costs reimbursed. Nostr.watch provides a unique, and valuable service for nostr users @dskvr

**Comment by alltheseas** [comment]
Congrats!!

**Comment by dskvr** [comment]
Yeah, you posted this before they announced it so I couldn't say anything yet :)

**Comment by alltheseas** [comment]
Well deserved, ser!
