### ISSUE TITLE
NIP-11 request does not use path

### ISSUE THREAD

**Issue by C-Otto** [dskvr/nostr-watch#645]
**Describe the bug**
When checking a relay that provides the data at a non-root path (e.g. wss://ftp.halifax.rwth-aachen.de/nostr), the NIP-11 check fails. It seems the root URL (https://ftp.halifax.rwth-aachen.de/) is used instead of the correct URL (https://ftp.halifax.rwth-aachen.de/nostr).

**To Reproduce**
Go to https://nostr.watch/relay/ftp.halifax.rwth-aachen.de/nostr

**Expected behavior**
NIP-11 info document should be OK.

**Comment by dskvr** [comment]
Good catch, easy patch.

**Comment by dskvr** [comment]
Hit some bumps when updating the package in the app, will reattempt today.

**Comment by dskvr** [comment]
Fixed: https://deploy-preview-647--nostrwatch.netlify.app/relay/ftp.halifax.rwth-aachen.de/nostr

Deploying, will be on production in ~5 minutes.
