### ISSUE TITLE
Page alerts about relay but doesn't provide details

### ISSUE THREAD

**Issue by Giszmo** [dskvr/nostr-watch#77]
The page "warns" about my relay.nostr.info that it returned five events when asking for one but I don't know which query this was or what these extra replies were. I'd like to fix this but ... miss info.

Since Jack joined nostr, my relay is basically dead, so there probably is an issue but details would be great.

**Comment by dskvr** [comment]
Hey, sorry about that! It's related to #22. A series of fixes and improvements are in the pipeline.

**Comment by dskvr** [comment]
This was resolved yesterday. Thanks for the report.
