### ISSUE TITLE
Website isn't showing my relay name and pubkey

### ISSUE THREAD

**Issue by nymsrelay** [dskvr/nostr-watch#81]
I edited my .nostr/settings.json file to show my relay's name and pubkey a couple of days ago, but I'm not seeing the changes. Is there somewhere else in my server's directory this file should be? This is the top section of the settings.json file.

root@nymsrelay:~/.nostr# cat settings.json

{
  "info": {
    "relay_url": "wss://nostr.nymsrelay.com",
    "name": "Nym's Relay",
    "description": "A nostr relay written in Typescript.",
    "pubkey": "bcea2b98506d1d5dd2cc0455a402701e342c76d70f46e38739aadde77ccef3c9",

**Comment by dskvr** [comment]
You need to have the appropriate headers set, or there will be a cors issue. See this nip for info: https://github.com/nostr-protocol/nips/blob/master/11.md

**Comment by dskvr** [comment]
I see that you figured it out, closing 
![Screen Shot 2022-12-20 at 9 43 34 PM](https://user-images.githubusercontent.com/299465/208762753-c6d71726-0324-4fb7-9aa6-8f24e37f4fb3.png)
